name: C/C++ Nightly arm macos

on:
  push:
    branches:
      - Nigthly
      - nightly_dev
      - nightly_master
      - debug_macos

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: build deps & slicer
      run: ./BuildMacOS.sh -ia
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_arm_debug.dmg
        path: build/${{ github.event.repository.name }}.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_arm_macos.tar
        path: build/${{ github.event.repository.name }}.tar
